name: Test & build
on:
  pull_request:

jobs:
  ci:
    name: Test & build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '15'

      - name: Install dependencies npm install
        run: npm ci

      - name: Linter (ESLint) npm run lint
        run: npm run lint

      - name: Formatter (Prettier) npm run prettier
        run: npm run prettier

      - name: Test (Jest) CI=true npm run test
        run: npm run test

      - name: Build npm run build
        run: npm run build
